apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: demo-db
  labels:
    app: demo-db
spec:
  serviceName: "demo-db"
  replicas: {{.Values.StatefulSet.replicas}}
  selector:
    matchLabels:
      app: demo-db
  template:
    metadata:
      labels:
        app: demo-db
    spec:
      containers:
        - name: postgresql
          image: {{ .Values.StatefulSet.image}}:{{.Values.StatefulSet.tag }}
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: demo-db
                  key: username
            - name: POSTGRES_PASS
              valueFrom:
                secretKeyRef:
                  name: demo-db
                  key: password
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: demo-db
                  key: database
            - name: POSTGRES_URL
              value: "jdbc:postgresql://demo-db:5432/petclinic"  # Correct PostgreSQL URL
          ports:
            - containerPort: {{.Values.db.port}}
              name: postgresql
          volumeMounts:
            - name: data-volume
              mountPath: /var/lib/postgresql/data
          livenessProbe:
            
            tcpSocket:
              port: postgresql
          readinessProbe:
            tcpSocket:
              port: postgresql
          startupProbe:
            tcpSocket:
              port: postgresql
  volumeClaimTemplates:
    - metadata:
        name: data-volume
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 1Gi