
apiVersion: v1
kind: Secret
metadata:
  name: demo-db
  labels:
    app.kubernetes.io/managed-by: Helm  # Helps Helm manage this secret if it's created by it
    meta.helm.sh/release-name: {{ .Release.Name }}  # Helps Helm manage this secret within the release
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}  # Helps Helm manage this secret in the release's namespace

type: servicebinding.io/postgresql
stringData:
  type: "postgresql"
  provider: "postgresql"
  host: "demo-db"
  port: "{{.Values.db.port}}"
  database: "{{.Values.db.database}}"
  username: "{{.Values.db.username}}"
  password: "{{.Values.db.password}}"